export const UPDATE_SEARCH_RESULTS = 'UPDATE_SEARCH_RESULTS';
export const LOAD_FAVORITES = 'LOAD_FAVORITES';
export const FILTER_SEARCH_RESULTS = 'FILTER_SEARCH_RESULTS';
export const PAGE_CHANGE = 'PAGE_CHANGE';
